### ISSUE TITLE
CAP használatának megfontolása MassTransit helyett

### ISSUE THREAD

**Issue by tibitoth** [bmeviauav42/jegyzetek#9]
A https://github.com/dotnetcore/CAP jobb választásnak tűnik, mert ez azon felül, hogy szintén absztrakciós réteget húz az MQ fölé, még az outbox patternt is megvalósítja.

**Comment by akosdudas** [comment]
@tibitoth Belebotlottam ebbe az issue-ba, szerintem jó a MassTransit, én nem változtatnék, a MassTransit sokkal többet tud és outbox is van benne már.
